<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Mapster" Version="10.0.8" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.9" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pryde.Domain\Pryde.Domain.csproj" />
    <ProjectReference Include="..\Pryde.Persistence\Pryde.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Security\Interface\" />
  </ItemGroup>

</Project>
