services:
  migrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrator
    container_name: pryde-migrator
    environment:
      PrydeConnection__Host: ${POSTGRES_HOST}
      PrydeConnection__Port: ${POSTGRES_PORT}
      PrydeConnection__Database: ${POSTGRES_DB}
      PrydeConnection__Username: ${POSTGRES_USER}
      PrydeConnection__Password: ${POSTGRES_PASSWORD}
      PrydeConnection__SslMode: Require
      PrydeConnection__ChannelBinding: Require

      JwtSettings__Key: ${JWT_KEY}
      JwtSettings__Issuer: Pryde.Api
      JwtSettings__Audience: Pryde.Client
      JwtSettings__AccessTokenExpiryMinutes: "60"
      JwtSettings__RefreshTokenExpiryDays: "30"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: pryde-api
    restart: unless-stopped
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      PrydeConnection__Host: ${POSTGRES_HOST}
      PrydeConnection__Port: ${POSTGRES_PORT}
      PrydeConnection__Database: ${POSTGRES_DB}
      PrydeConnection__Username: ${POSTGRES_USER}
      PrydeConnection__Password: ${POSTGRES_PASSWORD}
      PrydeConnection__SslMode: Require
      PrydeConnection__ChannelBinding: Require

      JwtSettings__Key: ${JWT_KEY}
      JwtSettings__Issuer: Pryde.Api
      JwtSettings__Audience: Pryde.Client
      JwtSettings__AccessTokenExpiryMinutes: "60"
      JwtSettings__RefreshTokenExpiryDays: "30"

      CloudinarySettings__CloudName: ${CLOUDINARY_CLOUD_NAME}
      CloudinarySettings__ApiKey: ${CLOUDINARY_API_KEY}
      CloudinarySettings__ApiSecret: ${CLOUDINARY_API_SECRET}

    ports:
      - "8080:8080"