<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pryde.Domain\Pryde.Domain.csproj" />
    <ProjectReference Include="..\Pryde.Persistence\Pryde.Persistence.csproj" />
    <ProjectReference Include="..\Pryde.Services\Pryde.Services.csproj" />
  </ItemGroup>

</Project>
